### ISSUE TITLE
divide by zero in simplex_projection function

### ISSUE THREAD

**Issue by gkiehne** [quantopian/quantopian-algos#1]
Thomas,

Please take a look at this code in simplex_projection:

for j in range(p): 
       if (u[j] - (np.sum(u[:j])-z) / j <= 0): 
           break

It appears that for j = 0, there will be a divide by zero error (flagged in Spyder on my pc when I tried the function).  I think that the bug is a carry-over from MATLAB, which indexes starting with 1.

Grant

**Comment by twiecki** [comment]
OK, I used another implementation I found. I think even the original I used before was broken. See if that works as expected.

**Comment by gkiehne** [comment]
Thanks Thomas,

There still seems to be a problem.  When I call simplex_projection in Spyder with:

proj = simplex_projection([.4 ,.3, -.4, .5])
print proj
print proj.sum()

I get:

[ 0.25  0.15  0.    0.35]
0.75

Also, this warning:

RuntimeWarning: divide by zero encountered in divide
  rho = np.where(u > (sv - b) / np.arange(p))[0][-1]

Grant

**Comment by gkiehne** [comment]
Thomas,

It looks like you used the wrong MATLAB code as the basis for the Python implementation of simplex_projection.  It should be this one, with b = 1:

http://www.cs.berkeley.edu/~jduchi/projects/DuchiShSiCh08/ProjectOntoSimplex.m

---

function w = ProjectOntoSimplex(v, b)
% PROJECTONTOSIMPLEX Projects point onto simplex of specified radius.
%
% w = ProjectOntoSimplex(v, b) returns the vector w which is the solution
%   to the following constrained minimization problem:
%
%    min   ||w - v||_2
%    s.t.  sum(w) <= b, w >= 0.
%
%   That is, performs Euclidean projection of v to the positive simplex of
%   radius b.
%
% Author: John Duchi (jduchi@cs.berkeley.edu)

if (b < 0)
  error('Radius of simplex is negative: %2.3f\n', b);
end
v = (v > 0) .\* v;
u = sort(v,'descend');
sv = cumsum(u);
rho = find(u > (sv - b) ./ (1:length(u))', 1, 'last');
theta = max(0, (sv(rho) - b) / rho);
w = max(v - theta, 0);

---

The references are:

http://machinelearning.org/archive/icml2008/papers/361.pdf
http://www.jmlr.org/papers/volume7/shalev-shwartz06a/shalev-shwartz06a.pdf

**Comment by twiecki** [comment]
Oops, sorry about that. Flipped a line. Should be all set now.

**Comment by gkiehne** [comment]
Still not quite working.  When I try to implement in Quantopian, I end up calling simplex_projection with v = [ 36.16958485, 36.16958485, 36.16958485] and it crashes.  If you try this in Spyder, you should get errors at:

rho = np.where(u > (sv - b) / np.arange(p))[0][-1]

**Comment by twiecki** [comment]
I forgot to port some other changes I made. Can you try again?

**Comment by gkiehne** [comment]
Seems o.k. now so I closed this issue.  Thanks!  If I get the chance today, I'll tinker around with the rebalancing.  Looks like it is just a few lines of code, so I'm not sure that we need a separate function for this project (although Quantopian should think about a general-purpose rebalance_portfolio function, including both long & short positions).

**Comment by twiecki** [comment]
OK, great. Sorry for the hick-ups.

Yeah, I suppose it will be easy to extract the function once we solved it
here.
