### ISSUE TITLE
simplex_projection working correctly?

### ISSUE THREAD

**Issue by gkiehne** [quantopian/quantopian-algos#3]
In Quantopian, and verified w/ Spyder, this code:

proj = simplex_projection([ 255.45139075, 8.33965118, 10.04146525, 49.38721184, 0.6844585, -20.54387549, -150.15763431, -7.80233517, -123.97035166, -20.42998088])
print proj

gives

[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]

This result seems incorrect (but admittedly, I don't yet understand the function).  For this case, why are all of the elements zero, except the first?  In the algorithm, this will result in shifting the portfolio to a single security.

**Comment by twiecki** [comment]
Yeah, I wondered the same thing. But it does make sense given the input numbers (one extremely large the other ones much smaller or negative). With more reasonable examples it works.

I think the problem is upstream to this (i.e. the Lambda).

**Comment by gkiehne** [comment]
Yes, I found the same thing by running the algorithm in Quantopian and adjusting context.eps to ~ 1.

**Comment by twiecki** [comment]
Does that help bring the numbers in a more meaningful range?

**Comment by gkiehne** [comment]
Yes, the algorithm appears to work more-or-less as expected with values of context.eps ~ 1 (I'd been using 10).  I'll have to put the testing aside for now, but should get back to it today/tomorrow.  By the way, I opened up another github issue to address the denom ~ 0 problem.
