### ISSUE TITLE
add handling of small or zero denom (low volatility case)

### ISSUE THREAD

**Issue by gkiehne** [quantopian/quantopian-algos#4]
Code needs to handle cases of small (~ 0) or zero values of denom:

denom = (np.linalg.norm((x_tilde-x_bar)))**2

**Comment by twiecki** [comment]
I think a case for when this is close to 0 to what you found in the other code will do, no?

**Comment by gkiehne** [comment]
In MATLAB, the author uses (based on the published PAMR code):

% Step 4: Set parameters
    x_bar = sum(data(t, :)) / N;
    denominator = (data(t, :) - x_bar)*(data(t, :) - x_bar)';
    if (~eq(denominator, 0.0)),
        tau = min([C, ell/denominator]);
    else
        tau = 0;
    end

However, I think that there may also be a low-volatility case (denom << 1) for which there will be a problem with the computation (in Python, I'm guessing that dividing by a small but non-zero value will either give an error or an incorrect result).  Perhaps you know how to manage this?

**Comment by twiecki** [comment]
Not sure what you mean. If the denom = 0 we don't update the portfolio essentially. Can you elaborate where we could run into problems with this check?

**Comment by gkiehne** [comment]
I tried the code below to cover the case of denom ~ 0, but it is not effective in avoiding a crash:

``` Python
# test for divide-by-zero case
    if denom == 0.0:
        lam = 0 # no portolio update
    else:     
        lam = max(0, num/denom)
```

If I set the window of the moving average to one day (mavg(1)), the code eventually generates an error, due to extremely big/small numbers under the quick daily backtest.  Effectively, this is emulating the rare (impossible?) zero-volatility case, but since denom is small but not quite zero, the code updates the portfolio and crashes.

So, I'm considering using a condition other than denom == 0.0 (e.g. denom < eps, where eps is a small positive non-zero number).

**Comment by twiecki** [comment]
Yeah, it'll never be exactly zero. Your proposal will work though.
