### ISSUE TITLE
cash goes negative

### ISSUE THREAD

**Issue by gkiehne** [quantopian/quantopian-algos#6]
With context.eps = 1.2, log.debug(context.portfolio.cash) results in:

2012-07-30 handle_data:50 DEBUG -43326700.6936

After initial order fullfilment, money should stay in portfolio with no further cash drawn.

As time allows, I try to sort out what is going on with the rebalancing and order submission/fulfilment.

**Comment by gkiehne** [comment]
I think we should turn off slippage & commissions for now...I'll see if I can sort this out.

**Comment by twiecki** [comment]
Yeah, there might still be a bug with the rebalance_portfolio. It didn't get to test it as thoroughly because of the prior problems.

**Comment by gkiehne** [comment]
Here's a re-write of rebalance_portfolio that seems to get the algorithm working correctly in Quantopian:

``` Python
def rebalance_portfolio(context, data, desired_port):
    #rebalance portfolio
    current_amount = np.zeros_like(desired_port)
    desired_amount = np.zeros_like(desired_port)

    if not context.init:
        positions_value = context.portfolio.starting_cash
    else:
        positions_value = context.portfolio.positions_value  

    for i, stock in enumerate(context.stocks):
        current_amount[i] = context.portfolio.positions[stock].amount
        desired_amount[i] = desired_port[i]*positions_value/data[stock].price

    diff_amount = desired_amount - current_amount

    for i, stock in enumerate(context.stocks):
        order(stock, diff_amount[i]) #order_stock
```

**Comment by twiecki** [comment]
Looks great! Do you want to update the code in the repo?

**Comment by gkiehne** [comment]
All set.  See update on github.com.  I also posted to Quantopian forum.

**Comment by gkiehne** [comment]
Link to Quantopian posting: https://www.quantopian.com/posts/update-olmar-implementation
